<?php

namespace Tests\Feature;

use App\Question;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ViewQuestionsTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
    }

//    public function testUserCanViewQuestions()
//    {
//        // 0. 抛出异常
//        $this->withoutExceptionHandling();
//        // 1.假设/questions 路由存在 2. 访问链接 /questions
//        $test = $this->get('/questions');
//        // 3. 正常返回 200
//        $test->assertStatus(200);
//    }

    // 推荐使用这种，具有更佳的可读性
    /** @test **/
    public function user_can_view_questions()
    {
        // 0. 抛出异常
        $this->withoutExceptionHandling();
        // 1.假设/questions 路由存在 2. 访问链接 /questions
        $test = $this->get('/questions');
        // 3. 正常返回 200
        $test->assertStatus(200);
    }

    /** @test **/
    public function user_can_view_a_single_question()
    {

        // 1. 创建一个问题
        $question = factory(Question::class)->create();
        // 2. 访问链接
        $test = $this->get('/questions/' . $question->id);
        // 3. 应该看到内容
        $test->assertStatus(200)
            ->assertSee($question->title)
            ->assertSee($question->content);
    }


}
